name: Publish

on: workflow_dispatch

jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§® Checkout code
        uses: actions/checkout@v3

      - name: ğŸ¦€ Build Rust
        run: "make web"

      - name: ğŸ”§ Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          cache-dependency-path: platforms/web/yarn.lock
          registry-url: "https://registry.npmjs.org"

      - name: ğŸ”¨ Install dependencies
        run: "yarn install --pure-lockfile"
        working-directory: platforms/web

      - name: ğŸªš Build
        run: "yarn build"
        working-directory: platforms/web

      - name: ğŸš€ Publish to npm
        id: npm-publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: platforms/web/package.json
          token: ${{ secrets.NPM_TOKEN }}
          access: public
