name: Publish

on: workflow_dispatch

jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§® Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”§ Yarn cache
        uses: actions/setup-node@v3
        working-directory: platforms/web
        with:
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: ğŸ”¨ Install dependencies
        run: "yarn install --pure-lockfile"
        working-directory: platforms/web

      - name: ğŸš€ Publish to npm
        id: npm-publish
        uses: JS-DevTools/npm-publish@v1
        working-directory: platforms/web
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

#      - name: ğŸ–ï¸ Add `latest` dist-tag to final releases
#        if: github.event.release.prerelease == false
#        run: |
#          package=$(cat package.json | jq -er .name)
#          npm dist-tag add "$package@$release" latest
#        working-directory: platforms/web
#        env:
#          # JS-DevTools/npm-publish overrides `NODE_AUTH_TOKEN` with `INPUT_TOKEN` in .npmrc
#          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
#          release: ${{ steps.npm-publish.outputs.version }}
