# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React build

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('react-build-main-{0}', github.sha) || format('react-build-pr-{0}', github.ref)  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Rust & Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: make web
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: platforms/web/yarn.lock
      - name: Typescript check
        working-directory: platforms/web
        run: yarn tsc
      - name: Lint check
        working-directory: platforms/web
        run: yarn lint
      - name: Test (with coverage!)
        working-directory: platforms/web
        run: yarn coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: platforms/web/coverage/lcov.info
          fail_ci_if_error: true
          flags: unittests-react, unittests
          # https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            platforms/web/coverage
            !platforms/web/coverage/lcov-report
            !platforms/web/coverage/tmp
      - name: Browser Test
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          working-directory: platforms/web
          start: yarn dev
